apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fbg-server
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas.fbgServer }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fbg-server
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fbg-server
    spec:
      containers:
      - env:
        - name: BGIO_PUBLIC_SERVERS
          value: https://{{ .Values.domain }}
        - name: BGIO_PRIVATE_SERVERS
          value: http://{{ .Release.Name }}-bgio
        - name: POSTGRES_URL
          value: postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.postgresqlDatabase }}
        - name: JWT_SECRET
          value: {{ .Values.fbgServer.jwtSecret }}
        image: shjgames/fbg-server
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ .Release.Name }}-fbg-server
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 350m
            memory: 384Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
