domain: www.sahajanand-games.com

replicas:
  web: 1
  fbgServer: 1
  bgio: 1

fbgServer:
  jwtSecret: SECRET_TO_SIGN_JWT

postgresql:
  postgresqlPostgresPassword: PG_ROOT_PASSWORD
  postgresqlUsername: fbgUser
  postgresqlPassword: PG_DB_PASSWORD
  postgresqlDatabase: fbgDb
  service:
    port: 5432
  volumePermissions:
    enabled: true